#!/bin/bash
# https://github.com/travis-ci/travis-ci/issues/1961

# Wrapper around 'brew install' emitting a message every minute if the command is still running.
# This is used on Travis to ensure the install isn't killed when there is no output over a long period (10 minutes).
# Usage: brew-install package, where package is the name of the package for brew to install.

brew install $@ &

while true; do
    sleep 60
    echo "brew install $@ still running"
    ps -p$! >/dev/null
    if [[ $? != 0 ]]; then
        exit
    fi
done
